server:
  port: 1488
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: demo2228
    url: jdbc:mysql://localhost:3306/task
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 3m
    refreshTokenExpiration: 10m